### ISSUE TITLE
Classes in JS and css

### ISSUE THREAD

**Issue by bn-l** [JorgeBucaran/classwrap#5]
Consider changing name. Thought this was something for cond inheritance.

**Comment by jbucaran** [comment]
@bn-l If you are going to go out of your way to open an issue, you may consider suggesting an alternative name along with your ticket? 🤔

**Comment by bn-l** [comment]
Very good point.

CssStyleConcat

**Comment by bn-l** [comment]
StyleWrap
CSSWrapUp
CondStyleWrap

I'm spent. I need a cigarette.

**Comment by jbucaran** [comment]
Please remember that this library is pretty much only intended to join **class names**. For that reason none of your suggestions that use the word `Style` really work.

I also spent some long time thinking about the name and discussed it with several peers, here are some of the other ideas I had in mind before I chose `classwrap`:

- classzip or zipclass
- classjoin or joinclass
- classconcat or concatclass
- classnames3

**Comment by bn-l** [comment]
Hmm, have spent a while now too and it is very hard. Maybe put something in the description to differentiate it.

**Comment by jbucaran** [comment]
@bn-l Ah, that's a good start, but I still think it's incorrect, because they are not strictly CSS class names.

They can be CSS class names as you say, but in reality you are just building the string that will be used for the [className](https://developer.mozilla.org/en-US/docs/Web/API/Element/className) property or [class] attribute.

Maybe "0.3 KB JavaScript utility for conditionally concatenating class names attributes" or change attribute for properties.

Tricky! :)

**Comment by loopmode** [comment]
I think the naming is pretty fine and semantics.
Consider that the most popular lib for this is `classnames` by jedwatson.

Typically I use it as this: `import cx from 'classnames';` and `className={cx('foo', 'bar', {baz})}`
Instead, in my next project, I will be doing `import cw from 'classwrap';` and `className={cx('[foo', 'bar', {baz}])}`

So.. I personally think it's just fine :)

**Comment by JorgeBucaran** [comment]
@loopmode I've been using `import cx from "classwrap"`, but now I think I like `cw` better! 😏👍 

@bn-l Thanks for the discussion.

**Comment by everdimension** [comment]
What was the original name?

**Comment by jorgebucaran** [comment]
@everdimension The original name was classwrap.
